export const routes = {
  home: '/',
  login: '/auth/login',
  register: '/auth/register',
  auth: '/auth',
  inbox: '/inbox',
  sell: '/sell',
  favorite: '/favorite',
  privacy: '/privacy',
  terms: './terms',
  bookmarks: './bookmarks',
  profile: './profile',
  users: './users/:id',
  listings: './listings/:id',
  search: './search',
  addProduct: '/products/add',
};
